_target_: src.models.mixture_von_mises_nll_based.MIXTURE_VONMISES_NLLSELDNet

dataset_path : audio/data/ansim
cv_fold_idx: 1

hparams : 
  name: 'MHMIXTURE_VONMISES_NLLSELDNet'
  max_num_sources: 3
  sequence_duration: 30
  num_fft_bins: 2048
  frame_length: 0.04
  chunk_length: 0.5
  hidden_dim: 128
  dropout_rate: 0
  learning_rate: 0.05
  num_epochs_warmup: 5
  num_modes: 2
  log_var_pred: False
  results_dir: null # Result directory with json files, additionnaly to the eval directory in the logs generated. 
  mode: 'wta'
  epsilon: 0.5
  top_n: 3
  distance: 'spherical'
  conf_weight: 1.
  rejection_method: 'all'
  number_unconfident: 3
  dist_type_eval: 'spherical'
  num_sources_per_sample_min: 0 # Number of sources considered > num_sources_per_sample_min 
  num_sources_per_sample_max: 3 # Number of sources considered <= num_sources_per_sample_max
  noisy_version: True
  sigma_points_mode: False
  N_samples_mog: 200
  N_samples_predicted_dist: 200
  data_loading_mode: 'normal'
  sigma_classes: [5,10,15,20,25,30,35,40,45,50,55]
  offline: False
  online: False
  online_val: False  
  compute_nll: False
  log_kappa_pred: True
  check_normalization_nll: False
