_target_: src.models.rmcl_based.MHConfSELDNet

dataset_path : audio/data/ansim
cv_fold_idx: 1

hparams : 
  name: 'MHCONFSELDNet'
  max_num_sources: 3
  sequence_duration: 30
  num_fft_bins: 2048
  frame_length: 0.04
  chunk_length: 0.5
  hidden_dim: 128
  dropout_rate: 0
  learning_rate: 0.05
  num_epochs_warmup: 5
  num_hypothesis: 2
  results_dir: null # Result directory with json files, additionnaly to the eval directory in the logs generated. 
  mode: 'wta'
  epsilon: 0.1
  top_n: 3
  distance: 'spherical'
  conf_weight: 1.
  rejection_method: 'all'
  number_unconfident: 3
  dist_type_eval: 'spherical'
  num_sources_per_sample_min: 0 # Number of sources considered > num_sources_per_sample_min 
  num_sources_per_sample_max: 3 # Number of sources considered <= num_sources_per_sample_max
  noisy_version: False
  sigma_points_mode: False
  N_samples_mog: 10
  data_loading_mode: 'normal'
  sigma_classes: [5,10,15,20,25,30,35,40,45,50,55]
  offline: False
  online: False
  online_val: False
  kernel_type: "von_mises_fisher"
  scaling_factor: 0.3
  closed_form_vol: True
  hit_and_run_sampling: False
  n_directions: 1000
  square_size: 1
  kernel_mode_emd: False
  compute_nll: False
  kde_mode: False
  kde_weighted: False
  num_modes: 3
